"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-u!gkp)1tq^tv8(zinsex)s+kba32)a)cq%el=6s%u4pz6+p4!!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['testserver', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_celery_results',
    'crm',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'growthops',
        'USER': 'admin',
        'PASSWORD': 'adminpassword',
        'HOST': 'postgres',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration Options
import os
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_TIMEZONE = "UTC"
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

# AI Provider Configuration
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Pipeline thresholds
# Leads scoring at or above this are eligible for automatic outreach drafting (docs/PDF: 70-75).
LEAD_SCORE_THRESHOLD = int(os.environ.get('LEAD_SCORE_THRESHOLD', 70))
# AI reply classifications below this confidence are routed to the Human Approval Queue (SRS 3.13).
REPLY_CONFIDENCE_THRESHOLD = float(os.environ.get('REPLY_CONFIDENCE_THRESHOLD', 0.85))
# A LeadSource is automatically re-scraped only after this many hours have passed.
SCRAPE_REFRESH_HOURS = int(os.environ.get('SCRAPE_REFRESH_HOURS', 24))

# --- TEST-MODE SAFETY ---------------------------------------------------
# While OUTREACH_TEST_MODE is on, EVERY outgoing email is redirected to
# TEST_REDIRECT_EMAIL no matter which lead it was drafted for. This makes it
# impossible to accidentally email a real scraped prospect during testing.
# The real recipient is preserved in the email's "X-Intended-Recipient" header
# and the audit log so you can still see who it *would* have gone to.
# Turn OFF (set OUTREACH_TEST_MODE=false) only when you are ready to go live.
OUTREACH_TEST_MODE = os.environ.get('OUTREACH_TEST_MODE', 'true').lower() in ('1', 'true', 'yes', 'on')
TEST_REDIRECT_EMAIL = os.environ.get('TEST_REDIRECT_EMAIL', os.environ.get('OUTREACH_EMAIL', ''))

LANGFUSE_SECRET_KEY = os.environ.get('LANGFUSE_SECRET_KEY', '')
LANGFUSE_PUBLIC_KEY = os.environ.get('LANGFUSE_PUBLIC_KEY', '')
LANGFUSE_HOST = os.environ.get('LANGFUSE_HOST', 'https://cloud.langfuse.com')

# --- LOGGING -----------------------------------------------------------
# Writes EVERYTHING (DEBUG+) to /app/logs/growthops.log inside the container.
# The backend volume is mounted at ./backend:/app, so on the host the file is
# at  backend/logs/growthops.log  — readable with:
#   tail -f backend/logs/growthops.log
# or via the /api/crm/logs/ streaming endpoint.
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] [{levelname}] [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'growthops.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 3,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
    'loggers': {
        # Our app code — DEBUG so every scrape step, task, and save is logged
        'crm': {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'scraper': {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'ai_engine': {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'outreach': {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        # Celery internals — INFO so we see task received/succeeded/failed
        'celery': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'celery.task': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        # Django request/db at WARNING (avoid noise)
        'django': {'handlers': ['console', 'file'], 'level': 'WARNING', 'propagate': False},
    },
}
