# Generated by Django 5.0.6 on 2026-06-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_approvalqueue_auditlog_suppressionlist_linkedintask'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('uncontacted', 'Uncontacted'), ('in_sequence', 'In Sequence'), ('replied', 'Replied'), ('disqualified', 'Disqualified')], default='uncontacted', max_length=50),
        ),
    ]
