# Generated by Django 5.0.6 on 2026-06-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_company_value_proposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='imap_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='imap_port',
            field=models.IntegerField(blank=True, default=993, null=True),
        ),
    ]
