# Generated by Django 5.0.6 on 2026-06-10 23:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


def dedupe_linkedin_urls(apps, schema_editor):
    """The old scrape fan-out attached the same (company) LinkedIn URL to many leads,
    which would violate the new per-lead uniqueness constraint. Keep the oldest
    lead's URL and null out the copies."""
    Lead = apps.get_model('crm', 'Lead')
    seen = set()
    for lead in Lead.objects.exclude(linkedin_url__isnull=True).order_by('created_at'):
        if lead.linkedin_url in seen:
            lead.linkedin_url = None
            lead.save(update_fields=['linkedin_url'])
        else:
            seen.add(lead.linkedin_url)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_emailaccount_imap_host_emailaccount_imap_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_enriched', 'Lead Enriched'), ('lead_scored', 'Lead Scored'), ('draft_created', 'Draft Created'), ('email_sent', 'Email Sent'), ('reply_received', 'Reply Received'), ('reply_classified', 'Reply Classified'), ('linkedin_task_created', 'LinkedIn Task Created'), ('linkedin_task_completed', 'LinkedIn Task Completed'), ('lead_magnet_submitted', 'Lead Magnet Submitted'), ('lead_suppressed', 'Lead Suppressed')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='LeadMagnetSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='lead',
            name='unique_lead',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='imap_use_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='smtp_encryption',
            field=models.CharField(choices=[('tls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'None (local/mock servers only)')], default='tls', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_generic_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='recommended_lead_magnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_leads', to='crm.leadmagnet'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='crm.campaign'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('needs_review', 'Needs Review'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.RunPython(dedupe_linkedin_urls, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('linkedin_url__isnull', False)), fields=('linkedin_url',), name='unique_lead_linkedin'),
        ),
        migrations.AddField(
            model_name='activity',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.campaign'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadmagnetsubmission',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magnet_submissions', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadmagnetsubmission',
            name='lead_magnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='crm.leadmagnet'),
        ),
    ]
